---
- name: Check for the default Redis configuration secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-redis-configuration'
  register: _redis_configuration
  no_log: "{{ no_log }}"

# The default configuration should generally be a 'managed' configuration but the cost
# of dynamically setting the variable here isn't high and will help avoid odd issues.
- name: Set Redis configuration for the default Redis configuration
  ansible.builtin.set_fact:
    redis_type: "{{ _redis_configuration['resources'][0]['data']['type'] | default('') | b64decode }}"
    redis_config_secret: "{{ _redis_configuration['resources'][0]['metadata']['name'] }}"
    redis_mode: "{{ _redis_configuration['resources'][0]['data']['redis_mode'] | default('') | b64decode }}"
  when: _redis_configuration['resources'][0] is defined
