---
- name: Create default Redis configuration secret
  kubernetes.core.k8s:
    state: present
    apply: true
    wait: true
    definition: "{{ lookup('template', 'redis.secret.yaml.j2') | from_yaml }}"
  register: result
  no_log: "{{ no_log }}"

- name: Set Redis configuration values for the default Redis configuration
  ansible.builtin.set_fact:
    redis_type: "managed"
    redis_config_secret: "{{ ansible_operator_meta.name }}-redis-configuration"
    redis_mode: "standalone"
  when: result is succeeded
