---
apiVersion: v1
kind: Secret
metadata:
  name: awx-connection-secret
stringData:
  url: 'https://example-awx-awx.apps.aap-dev.ocp4.testing.ansible.com'
  token: 'redacted-token-value'
  ssl_verify: 'no'
