---

- name: Combine default and custom variables from the CR for each component
  set_fact:
    combined_api: "{{ _api | combine (api, recursive=True ) }}"
    combined_ui: "{{ _ui | combine (ui, recursive=True) }}"
    combined_worker: "{{ _worker | combine (worker, recursive=True) }}"
