---

- name: Combine default variables for components
  set_fact:
    combined_api: "{{ _api | combine(api, recursive=True) }}"
    combined_ui: "{{ _ui | combine(ui, recursive=True) }}"
    combined_scheduler: "{{ _scheduler | combine(scheduler, recursive=True) }}"
    combined_event_stream: "{{ _event_stream | combine(event_stream, recursive=True) }}"

# Backwards compatibility support for worker parameters
- name: Set defaults for workers # (overridden by worker, default_worker, and activation_worker)
  set_fact:
    combined_default_worker: "{{ _default_worker }}"
    combined_activation_worker: "{{ _activation_worker }}"

- name: Combine worker params
  set_fact:
    combined_default_worker: "{{ _worker | combine(worker, recursive=True) }}"
    combined_activation_worker: "{{ _worker | combine(worker, recursive=True) }}"
  when: worker is defined

- name: Set default worker parameters when worker is not defined
  set_fact:
    combined_default_worker: "{{ _default_worker | combine(default_worker, recursive=True) }}"
  when:
    - default_worker is defined

- name: Set activation worker parameters when worker is not defined
  set_fact:
    combined_activation_worker: "{{ _activation_worker | combine(activation_worker, recursive=True) }}"
  when:
    - activation_worker is defined
