---

- name: Import eda_object variables
  block:
  - name: Get EDA object definition from pvc
    kubernetes.core.k8s_exec:
      namespace: "{{ backup_pvc_namespace }}"
      pod: "{{ ansible_operator_meta.name }}-db-management"
      command: >-
        bash -c "cat '{{ backup_dir }}/eda_object'"
    register: eda_object

  - name: Create temp file for spec dict
    tempfile:
      state: file
    register: tmp_spec

  - name: Write spec vars to temp file
    copy:
      content: "{{ eda_object.stdout }}"
      dest: "{{ tmp_spec.path }}"
      mode: '0644'

  - name: Include spec vars to save them as a dict
    include_vars: "{{ tmp_spec.path }}"
