---

- name: Get secret definition from pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    command: >-
      bash -c "cat '{{ backup_dir }}/secrets.yml'"
  register: _secrets
  no_log: "{{ no_log }}"

- name: Create Temporary secrets file
  tempfile:
    state: file
    suffix: .json
  register: tmp_secrets

- name: Write vars to file locally
  copy:
    dest: "{{ tmp_secrets.path }}"
    content: "{{ _secrets.stdout }}"
    mode: 0640
  no_log: "{{ no_log }}"

- name: Include secret vars from backup
  include_vars: "{{ tmp_secrets.path }}"
  no_log: "{{ no_log }}"

- name: If deployment is managed, set the new postgres_configuration_secret name
  block:
  - name: Set new postgres_configuration_secret name
    set_fact:
      _generated_pg_secret_name: "{{ deployment_name }}-postgres-configuration"

  - name: Set tmp database dict
    set_fact:
      _tmp_database: "{{ spec['database'] | combine({'database_secret': _generated_pg_secret_name}, recursive=True) }}"
    no_log: "{{ no_log }}"

  - name: Override database_secret
    set_fact:
      spec:
        "{{ spec | combine({'database': _tmp_database}, recursive=True) }}"
  when: secrets['databaseConfigurationSecret']['data']['type'] | b64decode == 'managed'

- name: If deployment is managed, set the database_host in the pg config secret
  block:
    - name: Set new database host
      set_fact:
        database_host: "{{ deployment_name }}-postgres-{{ supported_pg_version }}"
      no_log: "{{ no_log }}"

    - name: Set tmp postgres secret dict
      set_fact:
        _pg_secret: "{{ secrets['databaseConfigurationSecret'] }}"
      no_log: "{{ no_log }}"

    - name: Change postgres host and name value
      set_fact:
        _pg_data: "{{ _pg_secret['data'] | combine({'host': database_host | b64encode }) }}"
        _pg_secret_name: "{{ deployment_name }}-postgres-configuration"
      no_log: "{{ no_log }}"

    - name: Override postgres secret name
      set_fact:
        _pg_secret: "{{ _pg_secret | combine({'name': _pg_secret_name}) }}"
      no_log: "{{ no_log }}"

    - name: Override postgres secret host with new Postgres service
      set_fact:
        _pg_secret: "{{ _pg_secret | combine({'data': _pg_data}) }}"
      no_log: "{{ no_log }}"

    - name: Create a new dict of secrets with the new postgres secret
      set_fact:
        secrets: "{{ secrets | combine({'databaseConfigurationSecret': _pg_secret}) }}"
      no_log: "{{ no_log }}"
  when: secrets['databaseConfigurationSecret']['data']['type'] | b64decode == 'managed'

- name: Apply secret
  k8s:
    state: present
    namespace: "{{ ansible_operator_meta.namespace }}"
    apply: yes
    wait: yes
    definition: "{{ lookup('template', 'secrets.yml.j2') }}"
  no_log: "{{ no_log }}"

- name: Remove ownerReference on restored secrets
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.value.name }}"
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  loop: "{{ secrets | dict2items }}"
  no_log: "{{ no_log }}"
