---

deployment_type: "eda"
supported_pg_version: 15
_postgres_image: quay.io/sclorg/postgresql-15-c9s
_postgres_image_version: latest

backup_api_version: '{{ deployment_type }}.ansible.com/v1alpha1'
backup_kind: 'EDABackup'

force_drop_db: false
pg_drop_create: ''
