---
# - name: Create the eda.ansible.com/v1beta1.EDABackup
#   k8s:
#     state: present
#     namespace: '{{ namespace }}'
#     definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
#     wait: yes
#     wait_timeout: 300
#     wait_condition:
#       type: Successful
#       status: "True"
#   vars:
#     cr_file: 'eda_v1beta1_edabackup.yaml'
#
# - name: Add assertions here
#   assert:
#     that: false
#     fail_msg: FIXME Add real assertions for your operator
