---
# vars file for EDA

api_server_name: "{{ ansible_operator_meta.name }}-api"
api_django_port: 8002        # port for Django app for nginx to proxy requests to
api_nginx_port: 8000  # nginx port for api endpoints and static files
websocket_server_name: "{{ ansible_operator_meta.name }}-daphne"
websocket_port: 8001
media_dir: /var/lib/eda/files
static_path: /var/lib/eda/static
bundle_ca_crt: ''

eda_event_stream_prefix_path: "{{ event_stream.prefix | default('/eda-event-streams') }}"
event_stream_nginx_port: 8000
event_stream_server_name: "{{ ansible_operator_meta.name }}-event-stream"
event_stream_django_port: 8002

# timeout defaults for nginx and gunicorn_workers
client_request_timeout: 30
gunicorn_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 3) | int }}'
gunicorn_timeout_grace_period: 2
eda_nginx_read_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 2) | int }}'

# Define which address to bind in the api, depending on the enabled IP version
api_bind_address: "{{ (ipv6_disabled | bool) | ternary('0.0.0.0', '[::]') }}"
