---

- name: Dump (generated) secret names from statuses and data into file
  include_tasks: dump_generated_secret.yml
  with_items:
    - dbFieldsEncryptionSecret
    - adminPasswordSecret
    - databaseConfigurationSecret

- name: Dump secret names from eda spec and data into file
  include_tasks: dump_secret.yml
  loop:
    - route_tls_secret
    - ingress_tls_secret
    - ldap_cacert_secret
    - bundle_cacert_secret
    - ee_pull_credentials_secret

# image_pull_secret is deprecated in favor of image_pull_secrets
- name: Dump image_pull_secret into file
  include_tasks: dump_secret.yml
  with_items:
    - image_pull_secret
  when: image_pull_secret is defined

- name: Dump image_pull_secrets into file
  include_tasks: dump_secret.yml
  with_items:
    - image_pull_secrets
  when: image_pull_secrets | default([]) | length

- name: Nest secrets under a single variable
  set_fact:
    secrets: {"secrets": '{{ secret_dict }}'}
  no_log: "{{ no_log }}"

- name: Write postgres configuration to pvc
  kubernetes.core.k8s_cp:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    remote_path: "{{ backup_dir }}/secrets.yml"
    content: "{{ secrets | to_yaml }}"
  no_log: "{{ no_log }}"
