---
apiVersion: v1
kind: Secret
metadata:
  name: 'eda-demo-external-database'
stringData:
  host: 'eda-postgresql'
  port: '5555'
  database: 'eda'
  username: 'eda'
  password: 'eda'
  sslmode: 'prefer'
  type: 'unmanaged'
type: Opaque
