apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda-demo
  annotations:
    "ansible.sdk.operatorframework.io/verbosity": "2"
spec:
  no_log: false
  automation_server_url: http://foo.bar
  ingress_type: ingress
