apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  name: eda-demo
  annotations:
    "ansible.sdk.operatorframework.io/verbosity": "5"
spec:
  no_log: false
  automation_server_url: https://foo.bar
