---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure operator image is set
      fail:
        msg: |
          You must specify the OPERATOR_IMAGE environment variable in order to run the
          'default' scenario
      when: not operator_image

    - name: Set testing image
      command: '{{ kustomize }} edit set image testing={{ operator_image }}'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Set pull policy
      command: '{{ kustomize }} edit add patch --path pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Set testing namespace
      command: '{{ kustomize }} edit set namespace {{ namespace }}'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Ensure the test namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - name: Pre-create the "VSO-managed" event stream postgres secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: '{{ guard_test_event_stream_secret }}'
            namespace: '{{ namespace }}'
          stringData:
            username: eda_event_stream
            password: '{{ guard_test_sentinel }}'
            database: eda
            port: '5432'
            host: '{{ guard_test_pg_host }}'
            sslmode: prefer
            type: managed
      no_log: '{{ guard_test_no_log | default(true) }}'
