---
# tasks file for EDA

- name: Create EDA ServiceAccount
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', item + '.yaml.j2') }}"
  loop:
    - 'service_account'
  no_log: "{{ no_log }}"

- name: Patch Labels
  include_tasks: patch_labels.yml
