---

- name: Patching labels to EDA resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: '{{ api_version }}'
      kind: '{{ kind }}'
      name: '{{ ansible_operator_meta.name }}'
      namespace: '{{ ansible_operator_meta.namespace }}'
      metadata:
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels: '{{ lookup("template", "../common/templates/labels/common.yaml.j2") | from_yaml }}'
  when: set_self_labels | bool

- name: Build `additional_labels_items` labels from `additional_labels`
  block:
  - name: Look up details for this deployment
    kubernetes.core.k8s_info:
      api_version: "{{ api_version }}"
      kind: "{{ kind }}"
      name: "{{ ansible_operator_meta.name }}"
      namespace: "{{ ansible_operator_meta.namespace }}"
    register: this_eda

  - name: Select resource labels which are in `additional_labels`
    set_fact:
      additional_labels_items: >-
        {{ this_eda['resources'][0]['metadata']['labels']
           | dict2items | selectattr('key', 'in', additional_labels)
           | list
        }}
    when: this_eda['resources'][0]['metadata']['labels']
  when: additional_labels | length
