---

- name: Get list of deployments matching label selector
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ ansible_operator_meta.name }}"
  register: matching_deployments

- name: Scale down matching deployments for migration
  kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: Deployment
    name: "{{ item.metadata.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    replicas: 0
    wait: yes
  loop: "{{ matching_deployments.resources }}"
  when: matching_deployments.resources | length > 0

