---
# Determine and set event stream postgres configuration secret

- name: Check for specified event stream PostgreSQL configuration
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ event_stream.database_secret }}'
  register: _custom_event_stream_pg_config
  when:
    - event_stream is defined
    - event_stream.database_secret is defined
    - event_stream.database_secret | length
  no_log: "{{ no_log }}"

- name: Check for default event stream PostgreSQL configuration
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-event-stream-postgres-configuration'
  register: _default_event_stream_pg_config
  no_log: "{{ no_log }}"

- name: Set event stream PostgreSQL configuration based on if user secret exists
  ansible.builtin.set_fact:
    _event_stream_pg_config: '{{ _custom_event_stream_pg_config["resources"] | default([]) | length | ternary(_custom_event_stream_pg_config, _default_event_stream_pg_config) }}'
  no_log: "{{ no_log }}"

- name: Create event stream database configuration if no secret exists
  when: not _event_stream_pg_config['resources'] | default([]) | length
  block:
    - name: Create event stream database configuration
      kubernetes.core.k8s:
        apply: true
        definition: "{{ lookup('template', 'event-stream-postgres.secret.yaml.j2') }}"
      no_log: "{{ no_log }}"

    - name: Read event stream database configuration
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-event-stream-postgres-configuration'
      register: _generated_event_stream_pg_config
      no_log: "{{ no_log }}"

- name: Set event stream PostgreSQL configuration fact
  ansible.builtin.set_fact:
    event_stream_pg_config: '{{ _generated_event_stream_pg_config["resources"] | default([]) | length | ternary(_generated_event_stream_pg_config, _event_stream_pg_config) }}'
  no_log: "{{ no_log }}"

- name: Set actual event stream postgres secret name
  ansible.builtin.set_fact:
    __event_stream_database_secret: "{{ event_stream_pg_config['resources'][0]['metadata']['name'] }}"
  no_log: "{{ no_log }}"

- name: Store event stream database configuration vars
  ansible.builtin.set_fact:
    event_stream_postgres_user: "{{ event_stream_pg_config['resources'][0]['data']['username'] | b64decode }}"
    event_stream_postgres_pass: "{{ event_stream_pg_config['resources'][0]['data']['password'] | b64decode }}"
    event_stream_postgres_sslmode: "{{ event_stream_pg_config['resources'][0]['data']['sslmode'] | default('prefer' | b64encode) | b64decode }}"
  no_log: "{{ no_log }}"
