---

name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  molecule:
    runs-on: ubuntu-22.04
    name: molecule
    env:
      DOCKER_API_VERSION: "1.38"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          pip install -r molecule/requirements.txt

      - name: Install Collections
        run: |
          ansible-galaxy collection install -r molecule/requirements.yml

      - name: Run Molecule
        env:
          MOLECULE_VERBOSITY: 3
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        run: |
          sudo rm -f $(which kustomize)
          make kustomize
          KUSTOMIZE_PATH=$(readlink -f bin/kustomize) molecule test -s kind
