name: Promote Operator Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name for the tag of the release.'
        required: true

jobs:
  promote-staged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG_NAME for workflow_dispatch event
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - name: Set TAG_NAME for release event
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: 'main'
          depth: 0

      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d    # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Log into registry quay.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d    # v3.0.0
        with:
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Pull Stored Image and Publish to quay.io/${{ github.repository }}:${TAG_NAME}
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${TAG_NAME} \
            --tag quay.io/ansible/${{ github.repository }}:${TAG_NAME}

      - name: Pull Stored Image and Publish to quay.io/${{ github.repository }}:latest
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${TAG_NAME} \
            --tag quay.io/ansible/${{ github.repository }}:latest

      - name: Build Bundle Image
        run: |
          make bundle IMG=eda-server-operator:${{ github.event.inputs.version }} VERSION=${{ github.event.inputs.version }}
          make bundle-build BUNDLE_IMG=eda-server-operator-bundle:${{ github.event.inputs.version }}
          docker tag eda-server-operator-bundle:${{ github.event.inputs.version }} eda-server-operator-bundle:latest

      - name: Push Bundle Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator-bundle
          tags: ${{ github.event.inputs.version }}
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Catalog Image
        run: |
          make catalog-build CATALOG_IMG=eda-server-operator-catalog:${{ github.event.inputs.version }} BUNDLE_IMG=quay.io/ansible/eda-server-operator-bundle:${{ github.event.inputs.version }}
          docker tag eda-server-operator-catalog:${{ github.event.inputs.version }} eda-server-operator-catalog:latest

      - name: Push Catalog Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator-catalog
          tags: ${{ github.event.inputs.version }},latest
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
