name: Release Operator

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Log into registry quay.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Operator Image
        run: |
          IMG=eda-server-operator:${{ github.event.inputs.version }} make docker-buildx
          docker tag eda-server-operator:${{ github.event.inputs.version }} eda-server-operator:latest

      - name: Push Operator Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator
          tags: ${{ github.event.inputs.version }}
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push Operator Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator
          tags: latest
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Bundle Image
        run: |
          make bundle IMG=eda-server-operator:${{ github.event.inputs.version }} VERSION=${{ github.event.inputs.version }}
          make bundle-build BUNDLE_IMG=eda-server-operator-bundle:${{ github.event.inputs.version }}
          docker tag eda-server-operator-bundle:${{ github.event.inputs.version }} eda-server-operator-bundle:latest

      - name: Push Bundle Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator-bundle
          tags: ${{ github.event.inputs.version }}
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Catalog Image
        run: |
          make catalog-build CATALOG_IMG=eda-server-operator-catalog:${{ github.event.inputs.version }} BUNDLE_IMG=quay.io/ansible/eda-server-operator-bundle:${{ github.event.inputs.version }}
          docker tag eda-server-operator-catalog:${{ github.event.inputs.version }} eda-server-operator-catalog:latest

      - name: Push Catalog Image
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: eda-server-operator-catalog
          tags: ${{ github.event.inputs.version }},latest
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Generate operator.yaml
        run: make generate-operator-yaml VERSION=${{ github.event.inputs.version }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: true

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./operator.yaml
          asset_name: operator.yaml
          asset_content_type: application/yaml
